# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns a value of the correlation sum. No NAs assumed.
#'
#' @param x the vector
#' @param r distance coefficient
#' @export
corrSum <- function(x, r) {
    .Call('Rgrassproc_corrSum', PACKAGE = 'Rgrassproc', x, r)
}

#' An innter loop of a generalized correlation sum. For internal use only.
#' No NAs assumed.
#' @export
corrPartialCounts <- function(x, r) {
    .Call('Rgrassproc_corrPartialCounts', PACKAGE = 'Rgrassproc', x, r)
}

